name: Check Pull Request

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  SPACE_ID: ${{ secrets.SPACE_ID }}
  SITE_NAME: ${{ secrets.SITE_NAME_DEV }}

on:
  pull_request:
    branches:
      - "**"

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build with Gatsby
        env:
          PREFIX_PATHS: "true"
        run: npm run build
      - name: Run Tests
        run: npm run test
