name: BFDI CI
env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  SPACE_ID: ${{ secrets.SPACE_ID }}
on:
  push:
    branches: [prod, dev]
  pull_request:
    branches: [prod, dev]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
      - run: npm run imageUpdate
